### ISSUE TITLE
integrity check readme minor correction

### ISSUE THREAD

**Issue by thtranos** [lchdl/annotation_free_wmh_seg#1]
Greetings, the .bat file that is used from the integrity check is not ROBEX but runROBEX.bat (like runROBEX.sh) thus it always throws an error, recognizing it cannot be located. Changing the python code from ROBEX to the actual executable name solves the problem. Please correct me if I'm wrong, this is a speculation based on the newest ROBEX distribution.

**Comment by lchdl** [comment]
Hi thtranos, are you trying to run DeepWMH on Windows (since you mentioned **runROBEX.bat**)? **Trying to run DeepWMH on Windows systems is not recommended** as it may produce many strange errors during installation, and solving these can be tedious. You can **run DeepWMH on Linux-based systems instead**.

Based on your description, I have tested all the installation steps listed in README.md again using a clean environment (Ubuntu 16.04.6 LTS, Python 3.7.1), and made some necessary changes.

**NOTE**: You can also install **anaconda** (https://www.anaconda.com/), so that you can manage multiple Python versions in different virtual environments on the same machine.

**Comment by thtranos** [comment]
First of all, I want to thank you for replying fast. I really appreciate your dedication on keeping this awesome work online.

This issue here was not affecting me, I just found out that the ROBEX distribution has not any executable file named ROBEX while inside the integrity_check.py is inputing ROBEX_BIN as join_path(ROBEX_DIR, 'ROBEX'). Anyways, this is a secondary, utility class that is not of much importance just mentioned it, now I'll be jumping right to the other issue.

Thanks again,

Theodore Tranos
